__all__ = ['bar', 'baz']
some.__bases__
some.__class__
assert __debug__
__builtins__
__builtins__.len
print(__builtins__)
some.__dict__
some.__doc__
some.__file__
some.__members__
some.__metaclass__
some.__methods__
some.__module__
some.__mro__
some.__name__
some.__slots__
some.__subclasses__
some.__version__
some.__weakref__
some.__qualname__
some.__code__
some.__wrapped__
some.__signature__
some.__defaults__
some.__func__
some.__self__
some.__kwdefaults__
some.__matmul__
some.__imatmul__
some.__rmatmul__
some.__annotations__
some.__init_subclass__
some.__set_name__
some.__fspath__
some.__classcell__
some.__bytes__
some.__spec__
some.__path__
some.__prepare__
some.__package__
some.__traceback__
some.__closure__
some.__globals__
some.__match_args__
some.__notspecial__
